#!/bin/bash

echo "🔧 Manual User Fix Script"
echo "========================="
echo ""
echo "This script will help you manually create the user record and verify RLS policies."
echo ""
echo "The issue is that user ID '996d53ca-3a2c-40d4-9a9d-23f224bd4c30' exists in auth.users"
echo "but not in public.users, causing 404 errors."
echo ""
echo "Steps to fix:"
echo "1. Go to your Supabase project dashboard"
echo "2. Navigate to SQL Editor"
echo "3. Copy and paste the contents of MANUAL_USER_FIX.sql"
echo "4. Run the SQL"
echo ""
echo "This will:"
echo "✅ Check if the user exists in both tables"
echo "✅ Create the missing user record in public.users"
echo "✅ Verify RLS policies are working"
echo "✅ Test database access"
echo ""
echo "After running this, the 404/403 errors should be resolved!"
echo ""
echo "Press Enter to continue..."
read
